In [1]:
import pandas as pd
import os
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score
%matplotlib inline

In [17]:
df = pd.read_csv('./Resources/filmtv_movies - ENG.csv')
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.6,6.00,5.0,9,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40298,221040,Louis C.K.: Sorry,2021,Comedy,63,United States,Louis C.K.,Louis C.K.,6.0,NaN,6.0,1,Show recorded at the Madison Square Garden in ...,NaN,0,0,0,0,0
40299,221041,"Me, Natalie",1969,Comedy,111,United States,Fred Coe,"Patty Duke, James Farentino, Martin Balsam, Al...",8.0,NaN,8.0,1,"Brooklyn. Natalie Miller (Patty Duke), a girl ...",NaN,0,0,0,0,0
40300,221059,Il nero,1967,Drama,107,Italy,Giovanni Vento,"Joy Nwosu, Alessandra Dal Sasso, Andrea Checch...",6.0,6.00,NaN,1,"The hopes, the illusions, the daily vicissitud...",NaN,0,0,0,0,0
40301,221061,Operatsiya 'Y' i drugie priklyucheniya Shurika,1965,Comedy,95,Soviet Union,Leonid Gaidai,"Aleksandr Demyanenko, Mikhail Pugovkin, Alekse...",6.0,6.00,NaN,1,"Three episodes starring the excerpt Shurik, a ...",NaN,0,0,0,0,0
40302,221103,I dimma dold,1953,Thriller,88,Sweden,Lars-Eric Kjellgren,"Eva Henning, Sonja Wigert, Hjördis Petterson, ...",6.0,6.00,NaN,1,"On an evening of dense fog, director Walter Wi...",NaN,0,3,1,3,0

In [18]:
print(df.shape)

(40303, 19)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40303 entries, 0 to 40302
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   filmtv_id     40303 non-null  int64
 1   title         40303 non-null  object
 2   year          40303 non-null  int64
 3   genre         40208 non-null  object
 4   duration      40303 non-null  int64
 5   country       40292 non-null  object
 6   directors     40270 non-null  object
 7   actors        38251 non-null  object
 8   avg_vote      40303 non-null  float64
 9   critics_vote  35703 non-null  float64
 10  public_vote   39829 non-null  float64
 11  total_votes   40303 non-null  int64
 12  description   38848 non-null  object
 13  notes         18456 non-null  object
 14  humor         40303 non-null  int64
 15  rhythm        40303 non-null  int64
 16  effort        40303 non-null  int64
 17  tension       40303 non-null  int64
 18  erotism       40303 non-null  int64
dtypes: float64(3), int64(9), object(7)
memory usage: 5.8+ MB

In [20]:
df.drop_duplicates()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.6,6.00,5.0,9,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40298,221040,Louis C.K.: Sorry,2021,Comedy,63,United States,Louis C.K.,Louis C.K.,6.0,NaN,6.0,1,Show recorded at the Madison Square Garden in ...,NaN,0,0,0,0,0
40299,221041,"Me, Natalie",1969,Comedy,111,United States,Fred Coe,"Patty Duke, James Farentino, Martin Balsam, Al...",8.0,NaN,8.0,1,"Brooklyn. Natalie Miller (Patty Duke), a girl ...",NaN,0,0,0,0,0
40300,221059,Il nero,1967,Drama,107,Italy,Giovanni Vento,"Joy Nwosu, Alessandra Dal Sasso, Andrea Checch...",6.0,6.00,NaN,1,"The hopes, the illusions, the daily vicissitud...",NaN,0,0,0,0,0
40301,221061,Operatsiya 'Y' i drugie priklyucheniya Shurika,1965,Comedy,95,Soviet Union,Leonid Gaidai,"Aleksandr Demyanenko, Mikhail Pugovkin, Alekse...",6.0,6.00,NaN,1,"Three episodes starring the excerpt Shurik, a ...",NaN,0,0,0,0,0
40302,221103,I dimma dold,1953,Thriller,88,Sweden,Lars-Eric Kjellgren,"Eva Henning, Sonja Wigert, Hjördis Petterson, ...",6.0,6.00,NaN,1,"On an evening of dense fog, director Walter Wi...",NaN,0,3,1,3,0

In [21]:
df = df.dropna()

In [22]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.6,6.00,5.0,9,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
5,21,The Uranian Conspiracy,1978,Spy,117,"Italy, Germany, Israel","Gianfranco Baldanello, Menahem Golan","Fabio Testi, Janet Agren, Assaf Dayan, Siegfri...",4.8,3.50,6.0,3,Two Israeli secret agents discover that traffi...,"Action and chases for half of Europe, espionag...",1,2,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40147,216838,Pearl,2022,Horror,82,"Canada, United States",Ti West,"Mia Goth, David Corenswet, Tandi Wright, Matth...",7.5,8.00,7.0,14,The origins of the character of Pearl (already...,Prequel of the film X - A sexy horror story (2...,0,0,0,0,0
40187,217338,RRR (Rise Roar Revolt),2022,Action,187,India,S.S. Rajamouli,"N.T. Rama Rao Jr., Ram Charan Teja, Ajay Devgn...",6.2,7.00,5.0,8,"1920, India. A talented Indian child of the Go...",Indian epic film with very high budget that mi...,0,1,1,0,0
40208,217989,Goodnight Mommy,2022,Horror,91,United States,Matt Sobel,"Naomi Watts, Peter Hermann, Cameron Crovetti, ...",5.2,5.00,5.0,13,"Two twin kids go home, but there is something ...",Remake of the 2014 Austrian film of the same n...,0,0,0,1,0
40265,219152,Kærlighed for voksne,2022,Thriller,104,Denmark,Barbara Topsøe-Rothenborg,"Dar Salim, Sonja Richter, Sus Noreen Jondahl W...",7.4,7.00,8.0,7,Christian and Leonora are an apparently perfec...,"Based on the novel ""A faithful husband"" by Ann...",0,0,0,0,0
40271,219175,Balle perdue 2,2022,Thriller,98,France,Guillaume Pierret,"Stefi Celma, Alban Lenoir, Nelson Estevez, Viv...",5.5,5.00,6.0,4,The talented mechanic Lino has served his crim...,Vanish bullet sequel (2020),0,0,0,0,0