In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from pathlib import Path
from collections import Counter

In [2]:
# Loading the Dataset
file_path = Path('./Resources/clean_tvfilm.csv')
tvfilm_df = pd.read_csv(file_path)
tvfilm_df.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
1,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.6,6.00,5,9,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
2,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
3,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
4,21,The Uranian Conspiracy,1978,Spy,117,"Italy, Germany, Israel","Gianfranco Baldanello, Menahem Golan","Fabio Testi, Janet Agren, Assaf Dayan, Siegfri...",4.8,3.50,6,3,Two Israeli secret agents discover that traffi...,"Action and chases for half of Europe, espionag...",1,2,0,2,0

In [3]:
# get top 5 genres
top_5_genre=list(tvfilm_df['genre'].value_counts().head(n=5).index)
# [8, 5, 24, 13, 0]

tvfilm_df['genre_grouped']=tvfilm_df['genre'].apply(lambda x: x if x in top_5_genre else 999)
tvfilm_df['genre_grouped'].value_counts()

Drama       5159
Comedy      4883
999         4152
Thriller    1252
Horror       832
Action       795
Name: genre_grouped, dtype: int64

In [4]:
# binary indicator for US or not
tvfilm_df['is_us']=tvfilm_df['country']=='United States'

In [5]:
# get top 5 country
top_5_country=list(tvfilm_df['country'].value_counts().head(n=5).index)
# 

tvfilm_df['country_grouped']=tvfilm_df['country'].apply(lambda x: x if x in top_5_country else 'other')
tvfilm_df['country_grouped'].value_counts()

United States    7122
other            4160
Italy            3904
France            871
Great Britain     782
Japan             234
Name: country_grouped, dtype: int64

In [6]:
all_actors=tvfilm_df['actors'].str.cat(sep=', ')
actors_list=all_actors.split(', ')
actors_dict={}
for each_actor in actors_list: 
    if each_actor in actors_dict: 
        actors_dict[each_actor]+=1
    else: 
        actors_dict[each_actor]=1
actors_dict

{'Kim Rossi Stuart': 18,
 'Simona Cavallari': 5,
 'Ennio Fantastichini': 38,
 'Orso Maria Guerrini': 9,
 'Silli Togni': 3,
 'Maria Pia Calzone': 8,
 'Luciano Curreli': 3,
 'Francesco Maria Dominedò': 1,
 'Michael Craig': 4,
 'John Meillon': 4,
 'Eva Griffith': 1,
 'Graham Rouse': 1,
 'Robert Bettles': 1,
 'Alfred Bell': 1,
 'John Meillon Jr.': 1,
 'Mickey Rourke': 35,
 'Steve Guttenberg': 11,
 'Ellen Barkin': 20,
 'Daniel Stern': 9,
 'Kevin Bacon': 35,
 'Timothy Daly': 5,
 'Paul Reiser': 10,
 'Kelle Kipp': 1,
 'Colette Blonigan': 1,
 'Eduardo De Filippo': 18,
 'Peppino De Filippo': 51,
 'Clelia Matania': 19,
 'Paolo Stoppa': 44,
 'Nario Bernardi': 1,
 'Augusto Di Giovanni': 3,
 'Edwige Maul': 1,
 'Italia Marchesini': 1,
 'Fabio Testi': 23,
 'Janet Agren': 25,
 'Assaf Dayan': 1,
 'Siegfried Rauch': 4,
 'Oded Kotler': 1,
 'Gianni Rizzo': 5,
 'Herbert Fux': 6,
 'Gian Maria Volonté': 28,
 'Irene Papas': 20,
 'Gabriele Ferzetti': 39,
 'Salvo Randone': 13,
 'Laura Nucci': 2,
 'Mario Scaccia': 11,
 'Luigi Pistilli': 14,
 'Leopoldo Trieste': 26,
 'Don Johnson': 11,
 'Penelope Ann Miller': 19,
 'William Forsythe': 22,
 'Bob Balaban': 17,
 'Tate Donovan': 4,
 'Tim Reid': 3,
 'Michael Jeter': 6,
 'Brad Sullivan': 4,
 'Alan Steel': 4,
 'Mary Arden': 3,
 'Sergio Ciani': 5,
 'Ivano Davoli': 3,
 'Giovanna Galletti': 3,
 'Aïché Nana': 2,
 'Charlie Charun': 1,
 'Gilberto Mazzi': 1,
 'Christopher Walken': 53,
 'Sean Penn': 37,
 'Chris Penn': 23,
 'Mary Stuart Masterson': 12,
 'Millie Perkins': 5,
 'Eileen Ryan': 2,
 'Tracey Walter': 7,
 'David Strathairn': 27,
 'Kiefer Sutherland': 29,
 'Candy Clark': 7,
 'Julia Roberts': 32,
 'Patrick Bergin': 10,
 'Kevin Anderson': 9,
 'Elizabeth Lawrence': 1,
 'Kyle Secor': 4,
 'Claudette Nevins': 3,
 'Tony Abatemarco': 1,
 'Marita Geraghty': 1,
 'Harley Venton': 2,
 'Madonna': 11,
 'Warren Beatty': 10,
 'Sandra Bernhard': 1,
 'Antonio Banderas': 49,
 'Pedro Almodóvar': 2,
 'Bela Lugosi': 12,
 'John Archer': 3,
 'Wanda McKay': 1,
 "Dave O'Brien": 2,
 'Lew Kelly': 2,
 'Claudia Cardinale': 46,
 'Monica Vitti': 30,
 'Vittorio Gassman': 71,
 'Giancarlo Giannini': 61,
 'Renato Pozzetto': 42,
 'Charles Bronson': 35,
 'Linda Cristal': 6,
 'Al Lettieri': 7,
 'Lee Purcell': 3,
 'Sam Waterston': 11,
 'Kathleen Quinlan': 17,
 'Yaphet Kotto': 12,
 'Jeffrey DeMunn': 8,
 'Rob Lowe': 18,
 'Demi Moore': 21,
 'James Belushi': 22,
 'Elizabeth Perkins': 12,
 'George DiCenzo': 4,
 'Robin Thomas': 3,
 'Megan Mullally': 3,
 'Henry Fonda': 41,
 "Dan O'Herlihy": 14,
 'Walter Matthau': 34,
 'Dom DeLuise': 14,
 'Frank Overton': 2,
 'Edward Binns': 4,
 'Fritz Weaver': 3,
 'Larry Hagman': 2,
 'Tony Curtis': 30,
 'Jack Lemmon': 30,
 'Marilyn Monroe': 16,
 'Joe E. Brown': 2,
 'George Raft': 5,
 "Pat O'Brien": 9,
 'Nehemiah Persoff': 9,
 'Joan Shawlee': 2,
 'Walter Pidgeon': 16,
 'Ira Fürstenberg': 3,
 'Klaus Kinski': 27,
 'Tino Carraro': 9,
 'Marino Masé': 8,
 'Corrado Olmi': 3,
 'Giovanni Ivan Scratuglia': 6,
 'Guido Alberti': 5,
 'Dick Powell': 8,
 'Evelyn Keyes': 5,
 'Lee J. Cobb': 25,
 'Ellen Drew': 5,
 'Nina Foch': 6,
 'Thomas Gomez': 7,
 'Jim Bannon': 1,
 'Rodney Dangerfield': 5,
 'Keith Gordon': 3,
 'Sally Kellerman': 6,
 'Robert Downey jr.': 44,
 'Burt Young': 21,
 'Ned Beatty': 17,
 'Terry Farrell': 2,
 'Paxton Whitehead': 1,
 'M. Emmet Walsh': 11,
 'Adrienne Barbeau': 11,
 'Jessica Tandy': 13,
 'Morgan Freeman': 52,
 'Dan Aykroyd': 32,
 'Patty LuPone': 2,
 'Esther Rolle': 2,
 'Judge Reinhold': 14,
 'Maurine Mueller': 1,
 'Michael J. Pollard': 4,
 'Jeffrey Jones': 8,
 'Rhea Perlman': 2,
 'Brion James': 12,
 'Marlon Brando': 31,
 'Anjanette Comer': 2,
 'John Saxon': 21,
 'Emilio Fernández': 4,
 'Alex Montoya': 1,
 'Miriam Colon': 4,
 'Rafael Campos': 2,
 'Frank Silvera': 4,
 'Antonio Sabato': 16,
 'Luciana Paluzzi': 12,
 'Enrico Maria Salerno': 42,
 'Elio Zamuto': 6,
 'Ettore Manni': 28,
 'Bedy Moratti': 2,
 'Patty Duke': 8,
 'Rosemary Murphy': 5,
 'Richard Thomas': 7,
 'Sian Barbara Allen': 2,
 'Dennis Rucker': 1,
 'Anna Magnani': 22,
 'Nino Besozzi': 8,
 'Virgilio Riento': 15,
 'Lauro Gazzolo': 11,
 'Vito Annichiarico': 1,
 'Sandro Ruffini': 7,
 'Marisa Vernati': 1,
 'Aldo Silvani': 13,
 'Vittorio De Sica': 67,
 'Galeazzo Benti': 10,
 'Laura Gore': 6,
 'Zora Piazza': 1,
 'David Hemmings': 12,
 'Sam Wanamaker': 10,
 'Jennie Linden': 2,
 'Ian Richardson': 6,
 'Ralph Richardson': 20,
 'Pinkas Braun': 3,
 'Shane Rimmer': 3,
 'Tony Mathews': 1,
 'Christopher Godwin': 1,
 'Jerry Calà': 24,
 'Alba Parietti': 1,
 'Eva Grimaldi': 12,
 'Teo Teocoli': 14,
 'Mauro Di Francesco': 6,
 'Salvatore Marino': 1,
 'Franco Oppini': 6,
 'Piermaria Cecchini': 2,
 'Guido Nicheli': 3,
 'Nick Nolte': 40,
 'Jacqueline Bisset': 21,
 'Robert Shaw': 16,
 'Eli Wallach': 25,
 'Louis Gossett jr.': 12,
 'Dick Anthony Williams': 3,
 'Earl Maynard': 1,
 'Bob Minor': 1,
 'Raymond Massey': 12,
 'Ruth Gordon': 4,
 'Gene Lockhart': 7,
 'Mary Howard': 2,
 'Minor Watson': 4,
 'Alan Baxter': 2,
 'Harvey Stephens': 1,
 'Howard Da Silva': 6,
 'Dorothy Tree': 1,
 'Patsy Kensit': 11,
 'David Bowie': 9,
 "Eddie O'Connell": 1,
 'James Fox': 20,
 'Ray Davies': 1,
 'Mandy Rice-Davies': 1,
 'Eve Ferret': 2,
 'Tony Hippolyte': 1,
 'Ed Harris': 37,
 'Mary Elizabeth Mastrantonio': 12,
 'Michael Biehn': 16,
 'Leo Burmester': 2,
 'Todd Graff': 2,
 'John Bedford Lloyd': 2,
 'J.C. Quinn': 1,
 'Kimberly Scott': 1,
 'Gigi Sammarchi': 6,
 'Andrea Roncato': 16,
 'Simona Marchini': 6,
 'Gegia': 4,
 'Anna Kanakis': 4,
 'Mirella Banti': 2,
 'Cinzia Berni': 1,
 'Serena Grandi': 15,
 'Paola Barbara': 7,
 'Germana Paolieri': 7,
 'Miguel Ligero': 1,
 'Luis de Arnedillo': 1,
 'Rafael Navarro': 1,
 'Manuel Arbó': 3,
 'Carmen Arrojo': 1,
 'Aldo Fabrizi': 34,
 'Walter Chiari': 48,
 'Alberto Sordi': 95,
 'Mara Berni': 7,
 'Mario Riva': 20,
 'Riccardo Billi': 28,
 'Timothy Hutton': 22,
 'Kelly McGillis': 14,
 'Maureen Stapleton': 7,
 'Ann Wedgeworth': 2,
 'James Gammon': 6,
 'Mare Winningham': 12,
 'John Considine': 1,
 'Don Murray': 12,
 'Tim Daly': 5,
 'David Rasche': 6,
 'Amanda Plummer': 14,
 'Tom Petty': 2,
 'Joan Fontaine': 14,
 'Joseph Cotten': 29,
 'Françoise Rosay': 6,
 'Robert Arthur': 2,
 'Jimmy Lydon': 2,
 'Fortunio Bonanova': 9,
 'Clark Gable': 19,
 'Claudette Colbert': 14,
 'Walter Connolly': 4,
 'Roscoe Karns': 2,
 'Jameson Thomas': 1,
 'Alan Hale': 15,
 'Arthur Hoyt': 2,
 'Blanche Friderici': 4,
 'Franco Citti': 12,
 'Franca Pasut': 1,
 'Adriana Asti': 21,
 'Paola Guidi': 1,
 'Silvana Corsini': 2,
 'Luciano Conti': 3,
 'Luciano Gonini': 2,
 'Renato Capogna': 1,
 'Valerie Dumas': 1,
 'Marvin Sither': 1,
 'Catherine Malard': 1,
 'Julie Ravix': 1,
 'Sally Nyolo': 1,
 'Maka Kotto': 1,
 'François Maistre': 4,
 'Gina Lollobrigida': 29,
 'Andrea Checchi': 39,
 'Vittorio Duse': 3,
 'Lamberto Maggiorani': 3,
 'Maria Laura Rocca': 2,
 'Giuseppe Taffarel': 1,
 'Franco Bologna': 1,
 'Pietro Tordi': 6,
 'Giuliano Montaldo': 5,
 'Michael Caine': 66,
 'Valerie Perrine': 6,
 'Brenda Vaccaro': 9,
 'Leonard Rossiter': 3,
 'Billy Connolly': 13,
 'Dennis Dugan': 3,
 'Fulton MacKay': 3,
 'Jimmie Walker': 1,
 'Dick Shawn': 4,
 'Gino Cervi': 41,
 'Mariella Lotti': 9,
 'Vanna Vanni': 3,
 'Carlo Lombardi': 3,
 'Annibale Betrone': 2,
 'Marina Doge': 2,
 'Wanda Capodaglio': 2,
 'Carl Weathers': 7,
 'Craig T. Nelson': 12,
 'Vanity': 3,
 'Sharon Stone': 32,
 'Thomas F. Wilson': 5,
 'Bill Duke': 8,
 'Robert Davi': 10,
 'Jack Thibeau': 5,
 'Buddy Ebsen': 8,
 'Keir Dullea': 6,
 'Warren Oates': 15,
 'Marie Windsor': 5,
 'Lois Nettleton': 4,
 'Barbara Luna': 1,
 'Alessandro Benvenuti': 18,
 'Francesco Nuti': 12,
 'Athina Cenci': 12,
 'Lucilla Baroni': 1,
 'Riccardo Cioni': 1,
 'Donata Genazzani': 1,
 'Paolo Hendel': 7,
 'Novello Novelli': 13,
 'Susan Hayward': 22,
 'Dean Martin': 16,
 'Wilfrid Hyde-White': 9,
 'Martin Balsam': 24,
 'Ralph Meeker': 6,
 'Frank Maxwell': 2,
 'Connie Sawyer': 1,
 'Ford Rainey': 1,
 'Erminio Macario': 17,
 'Isa Barzizza': 21,
 'Gianni Agus': 18,
 'Nigel Havers': 2,
 'Frank McRae': 4,
 'Marilyn Toduka': 1,
 'Gerry Lopez': 2,
 'Chang Wing Choy': 1,
 'Aki Aleong': 1,
 'Gary Cooper': 31,
 'Helen Hayes': 3,
 'Adolphe Menjou': 13,
 'Mary Philips': 2,
 'Jack La Rue': 3,
 'Mary Forbes': 1,
 'Gilbert Emery': 3,
 'Maria Denis': 3,
 'Adriano Rimoldi': 6,
 'Clara Calamai': 12,
 'Carlo Campanini': 33,
 'Bianca Della Corte': 1,
 'Carla Minello': 1,
 'Paolo Carlini': 7,
 'Brandon de Wilde': 3,
 'Walter Brennan': 15,
 'Sidney Poitier': 17,
 'Phil Harris': 1,
 'William Hopper': 3,
 'Louise Beavers': 2,
 'George Chandler': 3,
 'Robert Donat': 6,
 'Greer Garson': 9,
 'Paul Henreid': 7,
 'Terry Kilburn': 1,
 'John Mills': 14,
 'Judith Furse': 1,
 'Lyn Harding': 1,
 'Milton Rosmer': 1,
 'Michael Redgrave': 14,
 'Jean Kent': 3,
 'Nigel Patrick': 7,
 'Brian Smith': 1,
 'Bill Travers': 3,
 'Ronald Howard': 3,
 'Giorgio De Lullo': 4,
 'Tamara Lees': 7,
 'Leopoldo Valentini': 1,
 'Maria Grazia Francia': 6,
 'Charles Fawcett': 3,
 'Dante Maggio': 11,
 'John Hodiak': 7,
 'Leo Genn': 12,
 "Cathy O'Donnell": 2,
 'Reginald Owen': 10,
 'Anthony Bushell': 2,
 'Richard Gale': 1,
 'Anthony Perkins': 15,
 'Brigitte Bardot': 18,
 'Gregoire Aslan': 6,
 'Denise Provence': 1,
 'Jean-Marc Tennberg': 1,
 'Hans Verner': 1,
 'Jacques Monod': 3,
 'Dudley Moore': 8,
 'Nastassja Kinski': 24,
 'Armand Assante': 14,
 'Cassie Yates': 4,
 'Richard Libertini': 2,
 'Albert Brooks': 9,
 'Richard B. Shull': 2,
 'Gregory Peck': 37,
 'Deborah Kerr': 24,
 'Eddie Albert': 13,
 'Philip Ober': 6,
 'Herbert Rudley': 2,
 'John Sutton': 7,
 'Karin Booth': 2,
 'Marcello Mastroianni': 88,
 'Simone Signoret': 16,
 'Sandra Milo': 26,
 'Emmanuelle Riva': 6,
 'Domenico Modugno': 5,
 'Antoinette Weynen': 1,
 'Gina Rovere': 9,
 'Bibi Andersson': 13,
 'Elliott Gould': 20,
 'Max Von Sydow': 45,
 'Sheila Reid': 3,
 'Catherine Spaak': 29,
 'Nino Manfredi': 56,
 'Vittorio Caprioli': 34,
 'Maria Grazia Buccella': 16,
 'Mario Pisu': 10,
 'Gino Pernice': 7,
 'Akim Tamiroff': 13,
 'Marilù Tolo': 16,
 'Luigi Giuliani': 3,
 "Umberto D'Orsi": 23,
 'Bice Valori': 19,
 'Didi Perego': 15,
 'Francesco Mulè': 12,
 'Gino Bramieri': 14,
 'Robert Hays': 6,
 'Julie Hagerty': 7,
 'Leslie Nielsen': 21,
 'Lloyd Bridges': 14,
 'Peter Graves': 6,
 'Kareem Abdul-Jabbar': 2,
 'Robert Stack': 14,
 'Lorna Patterson': 1,
 'Frank Ashmore': 1,
 'Maureen McGovern': 1,
 'Judy Landers': 1,
 'Brett Cullen': 5,
 'Sherman Hemsley': 1,
 'Mary Cadorette': 1,
 'Don Most': 1,
 'Sandahl Bergman': 5,
 'Wendie Jo Sperber': 2,
 'Dennis Burkley': 2,
 'Raymond Burr': 11,
 'Chad Everett': 5,
 'Chuck Connors': 9,
 'Rip Thorn': 2,
 'John Dehner': 9,
 'William Shatner': 8,
 'Louis Seigner': 5,
 'Michael Lonsdale': 19,
 'Ivo Garrani': 15,
 'Jacques Spiesser': 3,
 'Roland Bertin': 5,
 'Henri Serre': 2,
 'Heinz Bennent': 6,
 'Hans Richter': 1,
 'Jean Gabin': 33,
 'Paul Crauchet': 5,
 'Pierre Forget': 1,
 'Gérard Depardieu': 64,
 'Victor Lanoux': 5,
 'Henri Vilbert': 2,
 'Geneviève Fontanel': 1,
 'Alberto Farnese': 12,
 'Bette Midler': 11,
 'Lily Tomlin': 12,
 'Fred Ward': 19,
 'Michele Placido': 58,
 'Edward Herrmann': 8,
 'Daniel Gerroll': 1,
 'Barry Primus': 5,
 'Michael Gross': 3,
 'Deborah Rush': 3,
 'Richard Gere': 38,
 'Andy Garcia': 24,
 'Nancy Travis': 9,
 'Laurie Metcalf': 7,
 'Richard Bradford': 11,
 'William Baldwin': 9,
 'Michael Beach': 8,
 'Katherine Borowitz': 7,
 'Kim Novak': 9,
 'Fred Astaire': 17,
 'Estelle Winwood': 4,
 'Lionel Jeffries': 5,
 'Maxwell Reed': 2,
 'Philippa Bevans': 1,
 'Henry Daniell': 10,
 'Whoopi Goldberg': 25,
 'Bob Goldthwait': 2,
 'G.W. Bailey': 2,
 'Lesley Ann Warren': 8,
 'James Handy': 3,
 'Anne De Salvo': 3,
 'John Goodman': 39,
 'Elizabeth Ruscio': 3,
 'Roberto Risso': 8,
 'Liam Redmond': 1,
 'Ralph Michael': 1,
 'Colin Douglas': 1,
 'Dinsdale Landen': 2,
 'Giuliano Gemma': 33,
 'Ursula Andress': 19,
 'Jack Palance': 30,
 'Giuseppe Maffioli': 4,
 'Luciana Turina': 4,
 'Rossana Di Lorenzo': 4,
 'Nello Pazzafini': 12,
 'Sophia Loren': 50,
 'Stephen Barclay': 1,
 'Umberto Melnati': 3,
 'Alessandro Fersen': 2,
 'Antonio Cifariello': 18,
 'Antonio Bardi': 1,
 'Masino Manunza': 1,
 'Osman Omar': 1,
 'Charles Grodin': 12,
 'Loryn Locklin': 2,
 'Stephen Elliott': 4,
 'Hector Elizondo': 23,
 'Mako': 7,
 'Veronica Hamel': 3,
 'Gates McFadden': 2,
 'George Lazenby': 3,
 'Diana Rigg': 6,
 'Telly Savalas': 22,
 'Ilse Steppat': 1,
 'Lois Maxwell': 13,
 'George Baker': 5,
 'Bernard Lee': 12,
 'Bernard Horsfall': 1,
 'Desmond Llewelyn': 7,
 'Sean Connery': 43,
 'Daniela Bianchi': 6,
 'Pedro Armendariz': 12,
 'Lotte Lenya': 2,
 'Eunice Gayson': 2,
 'Walter Gotell': 2,
 'Roger Moore': 27,
 'Christopher Lee': 41,
 'Britt Ekland': 7,
 'Maud Adams': 4,
 'Hervé Villechaize': 1,
 'Clifton James': 6,
 'Richard Loo': 5,
 'Akiko Wakabayashi': 3,
 'Donald Pleasence': 36,
 'Mie Hama': 3,
 'Tetsurô Tanba': 2,
 'Teru Shimada': 1,
 'Karin Dor': 1,
 'Claudine Auger': 14,
 'Adolfo Celi': 33,
 'Rik Van Nutter': 3,
 'Guy Doleman': 3,
 'Molly Peters': 1,
 'Martine Beswick': 1,
 'Jill St. John': 5,
 'Charles Gray': 4,
 'Lana Wood': 1,
 'Bruce Cabot': 14,
 'Jimmy Dean': 1,
 'Bruce Glover': 4,
 'Victor Mature': 16,
 'Piper Laurie': 18,
 'Vincent Price': 26,
 'William Bendix': 10,
 'Betta St. John': 4,
 'Steve Darrell': 2,
 'Marlo Dwyer': 1,
 'Walter Reed': 4,
 'Dennis Weaver': 6,
 'David Neidorf': 2,
 'Jennifer Jason Leigh': 30,
 'David Harris': 3,
 'Barry Corbin': 14,
 'Kathleen Wilhoite': 7,
 'Carmen Argenziano': 2,
 'Brad Leland': 2,
 'John Philbin': 3,
 'Lewis Jordan': 2,
 'Hélène Chanel': 12,
 'Claudie Lange': 6,
 'Umberto Raho': 8,
 'Cina Doren': 1,
 'Halina Zalewska': 3,
 'Danilo Turk': 1,
 'Anita Todesco': 2,
 'Giorgio Valletta': 1,
 'Mark Damon': 13,
 'Mary Young': 2,
 'Seyna Seyn': 1,
 'Stanley Kent': 2,
 'Aldo Bufi Landi': 11,
 'Isarco Ravaioli': 3,
 'Walter Neng': 1,
 'Franca Duccio': 1,
 'Bette Davis': 36,
 'Robert Wagner': 17,
 'Denholm Elliott': 14,
 'Gordon Jackson': 4,
 'Dudley Sutton': 4,
 'Catherine Schell': 1,
 'Pik Sen Lim': 1,
 'Paul Maxwell': 1,
 'David Healy': 2,
 'Katharine Hepburn': 25,
 'Kit Le Fever': 1,
 'Chip Zien': 1,
 'William Duell': 1,
 'Walter Abel': 5,
 'Elizabeth Wilson': 7,
 'Frances Pole': 1,
 'Edmund Purdom': 15,
 'Geneviève Page': 6,
 'Amparo Rivelles': 1,
 'José Guardiola': 2,
 'Félix Dafauce': 2,
 'Antonio Molino Rojo': 3,
 'Enrique Pelayo': 1,
 'Humphrey Bogart': 26,
 'Mary Astor': 11,
 'Sydney Greenstreet': 3,
 'Charles Halton': 1,
 'Victor Sen Yung': 1,
 'Roland Got': 1,
 'Lee Tung Foo': 1,
 'Frank Wilcox': 2,
 'Ronn Moss': 1,
 'Dona Speir': 1,
 'Hope Marie Carlton': 2,
 'Harold Diamond': 1,
 'Rodrigo Obregón': 2,
 'Cynthia Brimhall': 1,
 'Patty Duffek': 1,
 'Wolf Larson': 2,
 'Steve Reeves': 11,
 'Giorgia Moll': 14,
 'Scilla Gabel': 10,
 'Renato Baldini': 14,
 'Gérard Herter': 4,
 'Milivoje Zivanovic': 1,
 'Nikola Popovic': 1,
 'Jovan Gec': 2,
 'Jane Fonda': 26,
 'Anne Bancroft': 24,
 'Meg Tilly': 8,
 'Anne Pitoniak': 4,
 'Gratien Gelinas': 1,
 'Winston Rekert': 2,
 'Guy Hoffman': 1,
 'Gabriel Arcand': 1,
 'Françoise Faucher': 1,
 'Luciano Della Marra': 1,
 'Enrico Formichi': 2,
 'Afro Poli': 3,
 'Antonio Cassinelli': 1,
 'Domenico Balini': 1,
 'Mel Gibson': 28,
 'Ken Jenkins': 1,
 'David Marshall Grant': 2,
 'Lane Smith': 2,
 'Art LaFleur': 4,
 'Ned Eisenberg': 3,
 'Marshall Bell': 8,
 'James Stewart': 35,
 'Lee Grant': 10,
 'Jean Seberg': 10,
 'Olivia de Havilland': 19,
 'Darren McGavin': 5,
 'Robert Foxworth': 2,
 'Robert Hooks': 2,
 'Carol Kane': 14,
 'Alex Stapley': 1,
 'Holly Stapley': 1,
 'Géza Kovács': 1,
 'Errol Slue': 1,
 'Lou Pitoscias': 1,
 'Pierre Brice': 7,
 'Marisa Merlini': 37,
 'Memmo Carotenuto': 25,
 'Vicky Ludovici': 3,
 'Valeria Fabrizi': 16,
 'Marcello Paolini': 2,
 'Carlo Taranto': 13,
 'Lino Banfi': 57,
 'Mara Venier': 9,
 'Annie Belle': 7,
 'Franco Barbero': 2,
 'Pino Ammendola': 5,
 'Enzo Andronico': 24,
 'Rod Steiger': 34,
 'Fay Spain': 3,
 'James Gregory': 8,
 'Murvyn Vye': 3,
 'Robert Gist': 1,
 'Lewis Charles': 1,
 'Joe De Santis': 2,
 'Brian Keith': 16,
 'Kim Hunter': 5,
 'Paul Kelly': 6,
 'Kevin Coughlin': 2,
 'Joe Mantell': 2,
 'Sally Brophy': 1,
 'Howard Wierum': 1,
 'Curtis Cooksey': 2,
 'Horst Frank': 6,
 'Karin Kernke': 1,
 'Helmut Schmid': 1,
 'Paul Dahlke': 2,
 'Dieter Eppler': 2,
 'Kurt Müller-Graf': 1,
 'Christiane Maybach': 1,
 'Michel Simon': 11,
 'Lee Van Cleef': 22,
 'Graziella Granata': 6,
 'Lionel Stander': 15,
 'Gordon Mitchell': 16,
 'Bud Spencer': 31,
 'Ann Smyrner': 1,
 'Barry Newman': 7,
 'Harold Gould': 2,
 'Diana Muldaur': 3,
 'Robert Colbert': 1,
 'Kathleen Crowley': 1,
 'Warren J. Kemmerling': 2,
 'Booth Colman': 1,
 'Ken Swofford': 1,
 'Fred MacMurray': 13,
 'Joan Crawford': 21,
 'Conrad Veidt': 7,
 'Basil Rathbone': 18,
 'Richard Ainley': 1,
 'Cecil Cunningham': 1,
 'Ann Shoemaker': 2,
 'Marcel Cerdan': 1,
 'Ferruccio Tagliavini': 2,
 'Mischa Auer': 7,
 'Marilyn Buferd': 3,
 'Leonardo Cortese': 10,
 'Giuseppe Pierozzi': 2,
 'Cesare Polacco': 7,
 'Jacqueline Lustig': 4,
 'Martin Kalwill': 1,
 'Arturo Maly': 1,
 'Matthew Marsh': 3,
 'Enrique Ahriman': 1,
 'Cristina Czetto': 1,
 'Miguel Ángel Paludi': 1,
 'Mariano López': 1,
 'Amy Madigan': 7,
 'Ho Nguyen': 1,
 'Donald Moffat': 4,
 'Rudy Young': 1,
 'Truyen V. Tran': 1,
 'Cynthia Carle': 1,
 'Martin Lasalle': 1,
 'William Frankfather': 1,
 'Patrick Swayze': 18,
 'Lisa Niemi': 1,
 'Christopher Neame': 3,
 'Anthony Zerbe': 8,
 'John Fujioka': 2,
 'Brett Hool': 1,
 'Marcel Van Heerden': 1,
 'Arnold Vosloo': 14,
 'Rory Calhoun': 12,
 'David Brian': 7,
 'Alex Nicol': 1,
 'Kathleen Hughes': 1,
 'Edgar Buchanan': 9,
 'Mara Corday': 3,
 'Roy Roberts': 4,
 'Skip Homeier': 2,
 'Jules Berry': 3,
 'Arletty': 10,
 'Mady Berry': 1,
 'René Génin': 4,
 'Jacqueline Laurent': 1,
 'Bernard Blier': 28,
 'Arthur Devère': 1,
 'René Bergeron': 1,
 'Camillo Pilotto': 11,
 "Maurizio D'Ancora": 3,
 'Carla Candiani': 2,
 'Carlo Tamberlani': 9,
 'Dria Paola': 2,
 'Elio Steiner': 3,
 'Maria Schell': 7,
 'Karl Malden': 26,
 'George C. Scott': 26,
 'Karl Swenson': 2,
 'Virginia Gregg': 1,
 'John Dierkes': 4,
 'King Donovan': 5,
 'Montgomery Clift': 8,
 'Elizabeth Taylor': 27,
 'Eva Marie Saint': 12,
 'Lee Marvin': 20,
 'Rod Taylor': 17,
 'Agnes Moorehead': 18,
 'Elsa Merlini': 5,
 'Antonio Gandusio': 5,
 'Renato Cialente': 4,
 'Marcello Giorda': 2,
 'Olga Vittoria Gentilli': 1,
 'Margherita Bagni': 1,
 'Evi Maltagliati': 7,
 'Gianfranco Giachetti': 1,
 'Egisto Olivieri': 3,
 'Elisa Cegani': 17,
 'Gian Paolo Rosmino': 2,
 'Ugo Ceseri': 2,
 'Franco Coop': 6,
 'Umberto Sacripante': 5,
 'Omero Antonutti': 19,
 'Eva Kotamanidou': 3,
 'Grigoris Evangelatos': 1,
 'Mihalis Giannatos': 3,
 'Miranda Kounelaki': 1,
 'Laura De Marchi': 3,
 'Toula Stathopoulou': 1,
 'Thanos Grammenos': 1,
 'Shelley Winters': 30,
 'Jane Asher': 2,
 'Julia Foster': 1,
 'Millicent Martin': 1,
 'Shirley Anne Field': 2,
 'Vivien Merchant': 3,
 'Eleanor Bron': 7,
 'Dustin Hoffman': 35,
 'Stefania Sandrelli': 54,
 'Carla Gravina': 16,
 'Saro Urzì': 15,
 'Duilio Del Prete': 13,
 'Luigi Baghetti': 1,
 'Renzo Marignano': 5,
 'Danika La Loggia': 2,
 'Clara Colosimo': 6,
 'Enzo Cannavale': 39,
 'Prunella Ransome': 3,
 'Michael York': 17,
 'Colin Blakely': 8,
 'Ian McKellen': 24,
 'Peter Vaughan': 9,
 'Alan Dobie': 3,
 'Julian Glover': 10,
 'Laurence Olivier': 15,
 'Valerie Hobson': 5,
 'George Curzon': 2,
 'George Merritt': 2,
 'Gus McNaughton': 2,
 'David Tree': 2,
 'Sandra Storme': 1,
 'Nick Mancuso': 3,
 'David Warner': 12,
 'Kathryn Harrold': 4,
 'Stephen Macht': 4,
 'Strother Martin': 8,
 'George Clutesi': 1,
 'Ben Piazza': 2,
 'Donald Hotton': 1,
 'Ann Todd': 4,
 'Peter Cushing': 23,
 'Joan Plowright': 14,
 'Leo McKern': 10,
 'Paul Daneman': 2,
 'Alec McCowen': 7,
 'Renee Houston': 1,
 'Peter Van Eyck': 13,
 'Ruth Leuwerick': 1,
 'Charles Regnier': 2,
 'Sieghardt Rupp': 3,
 'Hannelore Elsner': 4,
 'Dieter Klein': 1,
 'Michael Janisch': 1,
 'Fritz Schmiedel': 1,
 'Tom Selleck': 17,
 'Paulina Porizkova': 4,
 'James Farentino': 2,
 'William Daniels': 8,
 'Hurd Hatfield': 3,
 'Ronald Guttman': 1,
 'Victor Argo': 9,

In [7]:
def sort_dict_by_value(d, reverse = False):
    return dict(sorted(d.items(), key = lambda x: x[1], reverse = reverse))

actors_dict=sort_dict_by_value(actors_dict, reverse=True)

In [8]:
top_100_actors=list(actors_dict.keys())[:100]
top_100_actors

['Alberto Sordi',
 'Marcello Mastroianni',
 'Ugo Tognazzi',
 'Vittorio Gassman',
 'Totò',
 'Ciccio Ingrassia',
 'Vittorio De Sica',
 'Franco Franchi',
 'Michael Caine',
 'Gérard Depardieu',
 'Robert De Niro',
 'Giancarlo Giannini',
 'Donald Sutherland',
 'Luca Zingaretti',
 'Michele Placido',
 'Samuel L. Jackson',
 'Lino Banfi',
 'Harvey Keitel',
 'Nino Manfredi',
 'Rutger Hauer',
 'Stefania Sandrelli',
 'Willem Dafoe',
 'Christopher Walken',
 'Nicolas Cage',
 'Julianne Moore',
 'Morgan Freeman',
 'Bruce Willis',
 'Mario Carotenuto',
 'Peppino De Filippo',
 'Christian De Sica',
 'Sophia Loren',
 'Alain Delon',
 'Valerio Mastandrea',
 'Antonio Banderas',
 'Franco Nero',
 'Alessandro Haber',
 'Liam Neeson',
 'Walter Chiari',
 'Sylva Koscina',
 'Diego Abatantuono',
 'Tomas Milian',
 'John Wayne',
 'Gene Hackman',
 'Robert Duvall',
 'Paolo Villaggio',
 'Claudia Cardinale',
 'Ornella Muti',
 'Margherita Buy',
 'Max Von Sydow',
 'Susan Sarandon',
 'John Turturro',
 'Paolo Stoppa',
 'Robert Downey jr.',
 'William Hurt',
 'Michel Piccoli',
 'Dennis Hopper',
 'Lando Buzzanca',
 'Robert Mitchum',
 'Laura Morante',
 'Sean Connery',
 'Edwige Fenech',
 'John Malkovich',
 'Anthony Hopkins',
 'Renato Pozzetto',
 'Enrico Maria Salerno',
 'Sigourney Weaver',
 'John Hurt',
 'Harrison Ford',
 'Virna Lisi',
 'Sergio Rubini',
 'Johnny Depp',
 'Valeria Golino',
 'Henry Fonda',
 'Gino Cervi',
 'Christopher Lee',
 'Jeff Bridges',
 'Catherine Deneuve',
 'Robin Williams',
 'Ben Kingsley',
 'Nick Nolte',
 'Alec Baldwin',
 'Dennis Quaid',
 'Danny DeVito',
 'Renzo Montagnani',
 'Forest Whitaker',
 'John Cusack',
 'Gabriele Ferzetti',
 'Andrea Checchi',
 'John Goodman',
 'Enzo Cannavale',
 'Philippe Leroy',
 'Massimo Boldi',
 'Meryl Streep',
 'Brad Pitt',
 'Giorgio Colangeli',
 'Riccardo Scamarcio',
 'Ennio Fantastichini',
 'Richard Gere',
 'Ernest Borgnine',
 'Anthony Quinn']

In [9]:
def has_top_actor(actor_list, top_list): 
    for each_actor in actor_list: 
        if each_actor in top_list: 
            return True
    return False

In [10]:
# get binary indicator
tvfilm_df['has_top_actor']=tvfilm_df['actors'].fillna('').apply(lambda x: has_top_actor(x.split(', '), top_100_actors))

In [11]:
# Creating a threshold for 'avg_vote' column
threshold = 7.0

# Creating a new column determining the films success
tvfilm_df['popular'] = tvfilm_df['avg_vote'].apply(lambda x: 0
                                                         if x >= threshold else 
                                                         1)

In [12]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

X = tvfilm_df[['effort', 'humor', 'rhythm', 'tension', 'erotism', 'year', 'duration', 'country_grouped', 'genre_grouped', 'has_top_actor']]
y = tvfilm_df['popular']

# creates one-hot encoding for desired columns
X = pd.get_dummies(X, columns=['genre_grouped', 'country_grouped'])

In [13]:
tvfilm_df.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,humor,rhythm,effort,tension,erotism,genre_grouped,is_us,country_grouped,has_top_actor,popular
0,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,2,0,Drama,False,Italy,True,1
1,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.6,6.00,...,1,2,1,0,0,999,True,United States,False,1
2,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,2,2,0,1,2,Comedy,True,United States,False,0
3,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,3,1,1,0,0,Comedy,False,Italy,True,1
4,21,The Uranian Conspiracy,1978,Spy,117,"Italy, Germany, Israel","Gianfranco Baldanello, Menahem Golan","Fabio Testi, Janet Agren, Assaf Dayan, Siegfri...",4.8,3.50,...,1,2,0,2,0,999,False,other,False,1

In [14]:
X.describe()

,effort,humor,rhythm,tension,erotism,year,duration,genre_grouped_999,genre_grouped_Action,genre_grouped_Comedy,genre_grouped_Drama,genre_grouped_Horror,genre_grouped_Thriller,country_grouped_France,country_grouped_Great Britain,country_grouped_Italy,country_grouped_Japan,country_grouped_United States,country_grouped_other
count,17073.000000,17073.000000,17073.00000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000,17073.000000
mean,1.037428,0.891583,2.02501,1.373279,0.482692,1988.394834,102.544075,0.243191,0.046565,0.286007,0.302173,0.048732,0.073332,0.051016,0.045803,0.228665,0.013706,0.417150,0.243660
std,1.233634,0.981624,0.82701,1.097787,0.742706,22.106267,22.918516,0.429022,0.210711,0.451906,0.459213,0.215313,0.260689,0.220037,0.209064,0.419985,0.116270,0.493103,0.429302
min,0.000000,0.000000,0.00000,0.000000,0.000000,1913.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,2.00000,0.000000,0.000000,1971.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,2.00000,1.000000,0.000000,1996.000000,99.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,2.000000,2.00000,2.000000,1.000000,2006.000000,110.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,5.000000,5.000000,5.00000,5.000000,4.000000,2022.000000,729.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
# Check the balance of our target values
y.value_counts()

1    12887
0     4186
Name: popular, dtype: int64

In [16]:
# Testing and training model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(12804, 20)

In [17]:
### OVERSAMPLING
## Native Random Oversampling
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 9665, 1: 9665})

In [18]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

/Users/kweeniehutjrs/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=1)

In [19]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.726521105793088

In [20]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 720,  327],
       [ 756, 2466]])

In [21]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.49      0.69      0.77      0.57      0.73      0.52      1047
          1       0.88      0.77      0.69      0.82      0.73      0.53      3222

avg / total       0.79      0.75      0.71      0.76      0.73      0.53      4269

In [22]:
### OVERSAMPLING: DURATION ###
## SMOTE Oversampleing
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(
    X_train, y_train
)
Counter(y_resampled)

Counter({0: 9665, 1: 9665})

In [23]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

/Users/kweeniehutjrs/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=1)

In [24]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6858071033848595

In [25]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 599,  448],
       [ 646, 2576]])

In [26]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.48      0.57      0.80      0.52      0.68      0.45      1047
          1       0.85      0.80      0.57      0.82      0.68      0.47      3222

avg / total       0.76      0.74      0.63      0.75      0.68      0.46      4269

In [27]:
### UNDERSAMPLING
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 3139, 1: 3139})

In [28]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

/Users/kweeniehutjrs/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=1)

In [29]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.6858071033848595

In [30]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 599,  448],
       [ 646, 2576]])

In [31]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.48      0.57      0.80      0.52      0.68      0.45      1047
          1       0.85      0.80      0.57      0.82      0.68      0.47      3222

avg / total       0.76      0.74      0.63      0.75      0.68      0.46      4269

In [32]:
### COMBINATION OF (OVER AND UNDER) SAMPBLING
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)
Counter(y_resampled)

Counter({0: 10738, 1: 7239})

In [33]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

/Users/kweeniehutjrs/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=1)

In [34]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.6858071033848595

In [35]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 799,  248],
       [1053, 2169]])

In [36]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.43      0.76      0.67      0.55      0.72      0.52      1047
          1       0.90      0.67      0.76      0.77      0.72      0.51      3222

avg / total       0.78      0.70      0.74      0.72      0.72      0.51      4269